name: Unittest

on:
  [push, pull_request]

permissions:
  contents: read

jobs:
  TestPackage:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
        os: ["ubuntu-latest", "macos-latest"]

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-java@v6
      with:
        distribution: 'temurin'
        java-version: '25'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv pip install -r requirements.txt --system
    - name: Lint with ruff
      run: |
        uv add --dev ruff   
        # Check unresolved formatting issues
        uv run ruff check . --show-fixes
    - name: Test basic functionality with unittest
      run: |
        export PYTHONPATH=$(pwd)/src
        uv pip install owlready2
        uv run python -m unittest discover -s test -p test_*.py
